config/routes.rb
Rails.application.routes.draw do
  resources :isbs
  resources :isas
  resources :comments
  resources :images
  get 'request/User'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # resources :arts, :book
  # 
  # 
  # 
  # 
  # 
  resources :client
  resources :doc

  resources :arts do
    collection do
      post 'search'
    end
  	resources :booklists
  end

  resources :about_mes

  root 'arts#new'


  namespace :admin do
    resources :art_person
    resources :art_pen
  end

  namespace :request do
    resources :user
    resources :bank
    resources :bank_branch
    resources :user_bank
    get 'error'
    get 'recharge/index'
    get 'recharge/new'
    post 'recharge/create'
    get 'recharge/contact'
    post 'recharge/contact_create'
  end

  namespace :free do
    # 天气
    get 'weather/index'
    post 'weather/search'
    post 'weather/create'
  end

  # 定义helper
  get 'helperuse/index'

  resources :images

  namespace :v1 do
  	get 'arts/hello'
    get 'weather/index'
  end

  namespace :admin do
    get '/' => 'home#index', as: :root # get '/', :to => 'home#index', as: :root get '/', to: 'home#index', as: :root
  end
end

app/models/about_me.rb
class AboutMe < ApplicationRecord
end

app/models/admin.rb
module Admin
  def self.table_name_prefix
    'admin_'
  end
end

app/models/art.rb
# require 'elasticsearch'
# require 'elasticsearch/model'
class Art < ApplicationRecord
	# has_many :booklist, dependent: :destroy
	# has_many :booklist, dependent: :delete_all
	# 

	# include Tire::Model::Search
	# include Elasticsearch::Model
  # include Elasticsearch::Model::Callbacks

  searchkick

	# def search_data
 #    { 
 #    	title: title,
 #      content: content 
 #    }
 #  end
  # Art.reindex
 

	has_one :booklist, dependent: :destroy
	validates :title, presence: true, 
	                  length: { minimum: 5 }


  
	# def self.elasticsearch(params = {}, options = {})
	#   key = params[:key].blank? ? "*" : params[:key] # 关键字
	#   params[:page] ||= 1 # 分页
	#   params[:per_page] ||= 20 # 每页条数
	#   # where_hash = {
	#   #   status: 'success', # 固定筛选值
	#   # }
	#   # conditions = {where: where_hash}
	#   conditions = {}
	#   conditions[:page] = params[:page]
	#   conditions[:per_page] = params[:per_page]
	#   search key, conditions
	# end


end

app/models/art_pen.rb
class ArtPen < ApplicationRecord
end

app/models/bank.rb
class Bank < ApplicationRecord
	has_many :bank_branch, class_name: 'BankBranch', foreign_key: "bank_id"
	belongs_to :user, foreign_key: "user_id"
end

app/models/booklist.rb
class Booklist < ApplicationRecord
  belongs_to :art
end

app/models/client.rb
class Client < ApplicationRecord
	has_and_belongs_to_many :docs
end

app/models/comment.rb
class Comment < ApplicationRecord
end

app/models/doc.rb
class Doc < ApplicationRecord
	before_save :update_base_attributes

  def download_url
    self.file.url
  end

  private
  def update_base_attributes
    if file.present? && file_changed?
      self.content_type = file.file.content_type
      self.file_size = file.file.size
    end
  end
end

app/models/document.rb
class Document < ApplicationRecord
end

app/models/free.rb
module Free
  def self.table_name_prefix
    'free_'
  end
end

app/models/helperuse.rb
class Helperuse < ApplicationRecord
end

app/models/image.rb
class Image < ApplicationRecord
	has_attached_file :avatar
	validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/
end

app/models/isa.rb
class Isa < ApplicationRecord
	has_many :isbs, :dependent => :destroy
end

app/models/isb.rb
class Isb < ApplicationRecord
  belongs_to :isa
end

app/models/recharge.rb
class Recharge < ApplicationRecord
	belongs_to :user
end

app/models/request.rb
module Request
  def self.table_name_prefix
    'request_'
  end
end

app/models/role.rb
class Role < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
	has_many :bank
	has_many :user_bank
	has_many :recharge

	mount_uploader :avatar, AvatarUploader
end

app/models/weather.rb
class Weather < ApplicationRecord
	def self.weather_data
		datas = Weather.all
	end
end

app/views/admin/_sidebar.html.erb
<div class="" style="width: 270px;float: left;">
	<div class="sidebar_box clearfix">
		<b class="sidebar">关联表</b>
		<ul class="sidebar">
			<li class="<%= is_active('isas', 'index', 'active') %>">
				<%= link_to '关联表(has_many && belongs_to)', isas_path, class:"color_dark" %>
			</li>
		</ul>
	</div>

	<div class="sidebar_box clearfix">
		<b class="sidebar">上传carrierwave</b>
		<ul class="sidebar">
			<li class="<%= is_active('client', 'index', 'active') %>">
				<%= link_to '上传-后台使用carrierwave', client_index_path, class:"color_dark" %>
			</li>
		</ul>
	</div>

	<div class="sidebar_box clearfix">
		<b class="sidebar">adminPage</b>
		<ul class="sidebar">
			<!-- <li><a href="/admin/art_person" style="color: rgba(0,0,0,0.5);">admin/art_person/indexOfpage</a></li> -->
			<li class="<%= is_active('admin/art_person', 'index', 'active') %>">
				<%= link_to 'admin/art_person/indexOfpage', admin_art_person_index_path, class:"color_dark" %>
			</li>
			<li class="<%= is_active('admin/art_pen', 'index', 'active') %>">
				<%= link_to 'admin/art_pen/indexOfpage', admin_art_pen_index_path, class:"color_dark" %>
			</li>
			<li class="<%= is_active('admin/art_pen', 'new', 'active') %>">
				<%= link_to 'admin/art_pen/newOfpage', new_admin_art_pen_path, class:"color_dark" %>
			</li>
		</ul>
	</div>
	<div class="sidebar_box clearfix">
		<b class="sidebar">Api</b>
		<ul class="sidebar">
			<li class="<%= is_active('free/weather', 'index', 'active') %>">
				<%= link_to '天气接口-https-get', free_weather_index_path, class:"color_dark" %>
			</li>
		</ul>
	</div>
	<div class="sidebar_box clearfix">
		<b class="sidebar">Helper</b>
		<ul class="sidebar">
			<li class="<%= is_active('helperuse', 'index', 'active') %>">
				<%= link_to 'helper用法', helperuse_index_path, class:"color_dark" %>
			</li>
		</ul>
	</div>
	<div class="sidebar_box clearfix">
		<b class="sidebar">upload——image</b>
		<ul class="sidebar">
			<li class="<%= is_active('image_path', 'index', 'active') %>">
				<%= link_to '上传图片', images_path, class:"color_dark" %>
			</li>
		</ul>
	</div>
	<div class="sidebar_box clearfix">
		<b class="sidebar">requestPage - no requeset</b>
		<ul class="sidebar">
			<li class="<%= is_active('request/bank', 'index', 'active') %>">
				<%= link_to '银行', request_bank_index_path, class:"color_dark" %>
			</li>
			<li class="<%= is_active('request/bank_branch', 'index', 'active') %>">
				<%= link_to '银行开户行', request_bank_branch_index_path, class:"color_dark" %>
			</li>
			<li class="<%= is_active('request/user_bank', 'index', 'active') %>">
				<%= link_to '用户银行卡', request_user_bank_index_path, class:"color_dark" %>
			</li>
			<li class="<%= is_active('request/user_bank', 'new', 'active') %>">
				<%= link_to '新建用户银行卡', new_request_user_bank_path, class:"color_dark" %>
			</li>
		</ul>
	</div>
	<div class="sidebar_box clearfix">
		<b class="sidebar">Recharge - no requeset</b>
		<ul class="sidebar">
			<li class="<%= is_active('request/recharge', 'index', 'active') %>">
				<%= link_to '充值列表', request_recharge_index_path, class:"color_dark" %>
			</li>
			<li class="<%= is_active('request/recharge', 'new', 'active') %>">
				<%= link_to '去充值', request_recharge_new_path, class:"color_dark" %>
			</li>
		</ul>
	</div>

</div>