config/routes.rb
Rails.application.routes.draw do
  resources :isbs
  resources :isas
  resources :comments
  resources :images
  get 'request/User'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # resources :arts, :book
  # 
  # 
  # 
  # 
  # 
  resources :client
  resources :doc

  resources :arts do
    collection do
      post 'search'
    end
  	resources :booklists
  end

  resources :about_mes

  root 'arts#new'


  namespace :admin do
    resources :art_person
    resources :art_pen
  end

  namespace :request do
    resources :user
    resources :bank
    resources :bank_branch
    resources :user_bank
    get 'error'
    get 'recharge/index'
    get 'recharge/new'
    post 'recharge/create'
    get 'recharge/contact'
    post 'recharge/contact_create'
  end

  namespace :free do
    # 天气
    get 'weather/index'
    post 'weather/search'
    post 'weather/create'
  end

  # 定义helper
  get 'helperuse/index'

  resources :images

  namespace :v1 do
  	get 'arts/hello'
    get 'weather/index'
  end

  namespace :admin do
    get '/' => 'home#index', as: :root # get '/', :to => 'home#index', as: :root get '/', to: 'home#index', as: :root
  end
end

app/models/about_me.rb
class AboutMe < ApplicationRecord
end

app/models/admin.rb
module Admin
  def self.table_name_prefix
    'admin_'
  end
end

app/models/art.rb
# require 'elasticsearch'
# require 'elasticsearch/model'
class Art < ApplicationRecord
	# has_many :booklist, dependent: :destroy
	# has_many :booklist, dependent: :delete_all
	# 

	# include Tire::Model::Search
	# include Elasticsearch::Model
  # include Elasticsearch::Model::Callbacks

  searchkick

	# def search_data
 #    { 
 #    	title: title,
 #      content: content 
 #    }
 #  end
  # Art.reindex
 

	has_one :booklist, dependent: :destroy
	validates :title, presence: true, 
	                  length: { minimum: 5 }


  
	# def self.elasticsearch(params = {}, options = {})
	#   key = params[:key].blank? ? "*" : params[:key] # 关键字
	#   params[:page] ||= 1 # 分页
	#   params[:per_page] ||= 20 # 每页条数
	#   # where_hash = {
	#   #   status: 'success', # 固定筛选值
	#   # }
	#   # conditions = {where: where_hash}
	#   conditions = {}
	#   conditions[:page] = params[:page]
	#   conditions[:per_page] = params[:per_page]
	#   search key, conditions
	# end


end

app/models/art_pen.rb
class ArtPen < ApplicationRecord
end

app/models/bank.rb
class Bank < ApplicationRecord
	has_many :bank_branch, class_name: 'BankBranch', foreign_key: "bank_id"
	belongs_to :user, foreign_key: "user_id"
end

app/models/booklist.rb
class Booklist < ApplicationRecord
  belongs_to :art
end

app/models/client.rb
class Client < ApplicationRecord
	has_and_belongs_to_many :docs
end

app/models/comment.rb
class Comment < ApplicationRecord
end

app/models/doc.rb
class Doc < ApplicationRecord
	before_save :update_base_attributes

  def download_url
    self.file.url
  end

  private
  def update_base_attributes
    if file.present? && file_changed?
      self.content_type = file.file.content_type
      self.file_size = file.file.size
    end
  end
end

app/models/document.rb
class Document < ApplicationRecord
end

app/models/free.rb
module Free
  def self.table_name_prefix
    'free_'
  end
end

app/models/helperuse.rb
class Helperuse < ApplicationRecord
end

app/models/image.rb
class Image < ApplicationRecord
	has_attached_file :avatar
	validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/
end

app/models/isa.rb
class Isa < ApplicationRecord
	has_many :isbs, :dependent => :destroy
end

app/models/isb.rb
class Isb < ApplicationRecord
  belongs_to :isa
end

app/models/recharge.rb
class Recharge < ApplicationRecord
	belongs_to :user
end

app/models/request.rb
module Request
  def self.table_name_prefix
    'request_'
  end
end

app/models/role.rb
class Role < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
	has_many :bank
	has_many :user_bank
	has_many :recharge

	mount_uploader :avatar, AvatarUploader
end

app/models/user_bank.rb
class UserBank < ApplicationRecord
	belongs_to :user
end

app/models/weather.rb
class Weather < ApplicationRecord
	def self.weather_data
		datas = Weather.all
	end
end

app/controllers/client_controller.rb
class ClientController < ApplicationController
	layout 'admin'

	def index
		client_id = 1
		client = Client.find(client_id)
		@clientImage = client.docs
	end

	def show
	end

	def create
		
	end

end

app/helpers/client_helper.rb
module ClientHelper
end

app/views/client/index.html.erb
client
<div>
	<% if @clientImage %>
		<% @clientImage.each do |i| %>
			<img src="<%= i.file %>" style="width: 80px;height: 50px;" />
		<% end %>
	<% end %>
</div>
<%= link_to 'new',new_client_path %>

app/views/client/new.html.erb
<div style="margin: 20px 0 0 350px;">
	<div>上传新建</div>
		<!-- <form action="/doc" method="post" enctype="multipart/form-data"> -->
			<!-- <input type="text" class="username" name="username" placeholder="username"></br> -->
			<!-- <input type="text" class="sex" name="sex" placeholder="sex"></br> -->
			<input type="file" name="file" id="file_upload">
	    <button id="sub_pic_btn">submit</button>
		<!-- </form> -->
</div>

<script type="text/javascript">
	var submitBtn = $('#sub_pic_btn');
	var timestamp = new Date().getTime();
	var token = Math.floor(Math.random() * 1000) + timestamp;
	var formData = new FormData();
	submitBtn.click(function () {
		var params = {};
		params.username = $('.username').val();
		params.sex = $('.sex').val();
		formData.append("file", $("#file_upload")[0].files[0]);//将文件塞入FormData

		console.log(formData)

		$.ajax({
			method: 'POST',
			data: formData,
			url: '/doc',
			dataType: 'json',
			processData: false,  // 告诉jQuery不要去处理发送的数据
      contentType: false,   // 告诉jQuery不要去设置Content-Type请求头
      // success: function (responseText) {
      //     alert(responseText);
      // }
		});
	});
  

	
</script>

app/views/client/show.html.erb
clientshow